spring.application.name=backend
# Configuraci�n de la base de datos SQLite
spring.datasource.url=jdbc:sqlite:safuhosting.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Configuraci�n de Hibernate/JPA para que entienda SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
# "update" hace que si cambiamos el c�digo, se actualice la tabla autom�ticamente
spring.jpa.hibernate.ddl-auto=update
# Esto nos mostrar� en consola qu� peticiones SQL se est�n haciendo
spring.jpa.show-sql=true

# Puerto donde escuchar� nuestro Backend
server.port=8080