spring.application.name=backend

spring.datasource.url=jdbc:sqlite:safuhosting.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=3000

safuhost.jwt.secret=${SAFUHOST_JWT_SECRET:safuhost_clave_secreta_super_larga_que_no_debe_compartirse_jamas_2026}
safuhost.jwt.duracion-ms=86400000

safuhost.frontend.origen=${SAFUHOST_FRONTEND_ORIGEN:https://safu-host-vercel.vercel.app}

safuhost.host-publico=${SAFUHOST_HOST_PUBLICO:safuhost.duckdns.org}
