spring.application.name=backend
# Configuración de la base de datos SQLite
spring.datasource.url=jdbc:sqlite:safuhosting.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Configuración de Hibernate/JPA para que entienda SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
# "update" hace que si cambiamos el código, se actualice la tabla automáticamente
spring.jpa.hibernate.ddl-auto=update
# Esto nos mostrará en consola qué peticiones SQL se están haciendo
spring.jpa.show-sql=true

# Puerto donde escuchará nuestro Backend
server.port=8080